// Computer_System_mm_interconnect_3.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module Computer_System_mm_interconnect_3 (
		input  wire        System_PLL_sys_clk_clk,                  //                System_PLL_sys_clk.clk
		input  wire        dma_2_reset_reset_bridge_in_reset_reset, // dma_2_reset_reset_bridge_in_reset.reset
		input  wire [27:0] dma_1_write_master_address,              //                dma_1_write_master.address
		output wire        dma_1_write_master_waitrequest,          //                                  .waitrequest
		input  wire [3:0]  dma_1_write_master_byteenable,           //                                  .byteenable
		input  wire        dma_1_write_master_chipselect,           //                                  .chipselect
		input  wire        dma_1_write_master_write,                //                                  .write
		input  wire [31:0] dma_1_write_master_writedata,            //                                  .writedata
		input  wire [27:0] dma_2_read_master_address,               //                 dma_2_read_master.address
		output wire        dma_2_read_master_waitrequest,           //                                  .waitrequest
		input  wire        dma_2_read_master_chipselect,            //                                  .chipselect
		input  wire        dma_2_read_master_read,                  //                                  .read
		output wire [31:0] dma_2_read_master_readdata,              //                                  .readdata
		output wire        dma_2_read_master_readdatavalid,         //                                  .readdatavalid
		output wire [15:0] intensity_sram_s1_address,               //                 intensity_sram_s1.address
		output wire        intensity_sram_s1_write,                 //                                  .write
		input  wire [7:0]  intensity_sram_s1_readdata,              //                                  .readdata
		output wire [7:0]  intensity_sram_s1_writedata,             //                                  .writedata
		output wire        intensity_sram_s1_chipselect,            //                                  .chipselect
		output wire        intensity_sram_s1_clken                  //                                  .clken
	);

	wire         dma_2_read_master_translator_avalon_universal_master_0_waitrequest;    // dma_2_read_master_agent:av_waitrequest -> dma_2_read_master_translator:uav_waitrequest
	wire  [31:0] dma_2_read_master_translator_avalon_universal_master_0_readdata;       // dma_2_read_master_agent:av_readdata -> dma_2_read_master_translator:uav_readdata
	wire         dma_2_read_master_translator_avalon_universal_master_0_debugaccess;    // dma_2_read_master_translator:uav_debugaccess -> dma_2_read_master_agent:av_debugaccess
	wire  [27:0] dma_2_read_master_translator_avalon_universal_master_0_address;        // dma_2_read_master_translator:uav_address -> dma_2_read_master_agent:av_address
	wire         dma_2_read_master_translator_avalon_universal_master_0_read;           // dma_2_read_master_translator:uav_read -> dma_2_read_master_agent:av_read
	wire   [3:0] dma_2_read_master_translator_avalon_universal_master_0_byteenable;     // dma_2_read_master_translator:uav_byteenable -> dma_2_read_master_agent:av_byteenable
	wire         dma_2_read_master_translator_avalon_universal_master_0_readdatavalid;  // dma_2_read_master_agent:av_readdatavalid -> dma_2_read_master_translator:uav_readdatavalid
	wire         dma_2_read_master_translator_avalon_universal_master_0_lock;           // dma_2_read_master_translator:uav_lock -> dma_2_read_master_agent:av_lock
	wire         dma_2_read_master_translator_avalon_universal_master_0_write;          // dma_2_read_master_translator:uav_write -> dma_2_read_master_agent:av_write
	wire  [31:0] dma_2_read_master_translator_avalon_universal_master_0_writedata;      // dma_2_read_master_translator:uav_writedata -> dma_2_read_master_agent:av_writedata
	wire   [2:0] dma_2_read_master_translator_avalon_universal_master_0_burstcount;     // dma_2_read_master_translator:uav_burstcount -> dma_2_read_master_agent:av_burstcount
	wire         rsp_mux_src_valid;                                                     // rsp_mux:src_valid -> dma_2_read_master_agent:rp_valid
	wire  [97:0] rsp_mux_src_data;                                                      // rsp_mux:src_data -> dma_2_read_master_agent:rp_data
	wire         rsp_mux_src_ready;                                                     // dma_2_read_master_agent:rp_ready -> rsp_mux:src_ready
	wire   [1:0] rsp_mux_src_channel;                                                   // rsp_mux:src_channel -> dma_2_read_master_agent:rp_channel
	wire         rsp_mux_src_startofpacket;                                             // rsp_mux:src_startofpacket -> dma_2_read_master_agent:rp_startofpacket
	wire         rsp_mux_src_endofpacket;                                               // rsp_mux:src_endofpacket -> dma_2_read_master_agent:rp_endofpacket
	wire         dma_1_write_master_translator_avalon_universal_master_0_waitrequest;   // dma_1_write_master_agent:av_waitrequest -> dma_1_write_master_translator:uav_waitrequest
	wire  [31:0] dma_1_write_master_translator_avalon_universal_master_0_readdata;      // dma_1_write_master_agent:av_readdata -> dma_1_write_master_translator:uav_readdata
	wire         dma_1_write_master_translator_avalon_universal_master_0_debugaccess;   // dma_1_write_master_translator:uav_debugaccess -> dma_1_write_master_agent:av_debugaccess
	wire  [27:0] dma_1_write_master_translator_avalon_universal_master_0_address;       // dma_1_write_master_translator:uav_address -> dma_1_write_master_agent:av_address
	wire         dma_1_write_master_translator_avalon_universal_master_0_read;          // dma_1_write_master_translator:uav_read -> dma_1_write_master_agent:av_read
	wire   [3:0] dma_1_write_master_translator_avalon_universal_master_0_byteenable;    // dma_1_write_master_translator:uav_byteenable -> dma_1_write_master_agent:av_byteenable
	wire         dma_1_write_master_translator_avalon_universal_master_0_readdatavalid; // dma_1_write_master_agent:av_readdatavalid -> dma_1_write_master_translator:uav_readdatavalid
	wire         dma_1_write_master_translator_avalon_universal_master_0_lock;          // dma_1_write_master_translator:uav_lock -> dma_1_write_master_agent:av_lock
	wire         dma_1_write_master_translator_avalon_universal_master_0_write;         // dma_1_write_master_translator:uav_write -> dma_1_write_master_agent:av_write
	wire  [31:0] dma_1_write_master_translator_avalon_universal_master_0_writedata;     // dma_1_write_master_translator:uav_writedata -> dma_1_write_master_agent:av_writedata
	wire   [2:0] dma_1_write_master_translator_avalon_universal_master_0_burstcount;    // dma_1_write_master_translator:uav_burstcount -> dma_1_write_master_agent:av_burstcount
	wire         rsp_mux_001_src_valid;                                                 // rsp_mux_001:src_valid -> dma_1_write_master_agent:rp_valid
	wire  [97:0] rsp_mux_001_src_data;                                                  // rsp_mux_001:src_data -> dma_1_write_master_agent:rp_data
	wire         rsp_mux_001_src_ready;                                                 // dma_1_write_master_agent:rp_ready -> rsp_mux_001:src_ready
	wire   [1:0] rsp_mux_001_src_channel;                                               // rsp_mux_001:src_channel -> dma_1_write_master_agent:rp_channel
	wire         rsp_mux_001_src_startofpacket;                                         // rsp_mux_001:src_startofpacket -> dma_1_write_master_agent:rp_startofpacket
	wire         rsp_mux_001_src_endofpacket;                                           // rsp_mux_001:src_endofpacket -> dma_1_write_master_agent:rp_endofpacket
	wire   [7:0] intensity_sram_s1_agent_m0_readdata;                                   // intensity_sram_s1_translator:uav_readdata -> intensity_sram_s1_agent:m0_readdata
	wire         intensity_sram_s1_agent_m0_waitrequest;                                // intensity_sram_s1_translator:uav_waitrequest -> intensity_sram_s1_agent:m0_waitrequest
	wire         intensity_sram_s1_agent_m0_debugaccess;                                // intensity_sram_s1_agent:m0_debugaccess -> intensity_sram_s1_translator:uav_debugaccess
	wire  [27:0] intensity_sram_s1_agent_m0_address;                                    // intensity_sram_s1_agent:m0_address -> intensity_sram_s1_translator:uav_address
	wire   [0:0] intensity_sram_s1_agent_m0_byteenable;                                 // intensity_sram_s1_agent:m0_byteenable -> intensity_sram_s1_translator:uav_byteenable
	wire         intensity_sram_s1_agent_m0_read;                                       // intensity_sram_s1_agent:m0_read -> intensity_sram_s1_translator:uav_read
	wire         intensity_sram_s1_agent_m0_readdatavalid;                              // intensity_sram_s1_translator:uav_readdatavalid -> intensity_sram_s1_agent:m0_readdatavalid
	wire         intensity_sram_s1_agent_m0_lock;                                       // intensity_sram_s1_agent:m0_lock -> intensity_sram_s1_translator:uav_lock
	wire   [7:0] intensity_sram_s1_agent_m0_writedata;                                  // intensity_sram_s1_agent:m0_writedata -> intensity_sram_s1_translator:uav_writedata
	wire         intensity_sram_s1_agent_m0_write;                                      // intensity_sram_s1_agent:m0_write -> intensity_sram_s1_translator:uav_write
	wire   [0:0] intensity_sram_s1_agent_m0_burstcount;                                 // intensity_sram_s1_agent:m0_burstcount -> intensity_sram_s1_translator:uav_burstcount
	wire         intensity_sram_s1_agent_rf_source_valid;                               // intensity_sram_s1_agent:rf_source_valid -> intensity_sram_s1_agent_rsp_fifo:in_valid
	wire  [71:0] intensity_sram_s1_agent_rf_source_data;                                // intensity_sram_s1_agent:rf_source_data -> intensity_sram_s1_agent_rsp_fifo:in_data
	wire         intensity_sram_s1_agent_rf_source_ready;                               // intensity_sram_s1_agent_rsp_fifo:in_ready -> intensity_sram_s1_agent:rf_source_ready
	wire         intensity_sram_s1_agent_rf_source_startofpacket;                       // intensity_sram_s1_agent:rf_source_startofpacket -> intensity_sram_s1_agent_rsp_fifo:in_startofpacket
	wire         intensity_sram_s1_agent_rf_source_endofpacket;                         // intensity_sram_s1_agent:rf_source_endofpacket -> intensity_sram_s1_agent_rsp_fifo:in_endofpacket
	wire         intensity_sram_s1_agent_rsp_fifo_out_valid;                            // intensity_sram_s1_agent_rsp_fifo:out_valid -> intensity_sram_s1_agent:rf_sink_valid
	wire  [71:0] intensity_sram_s1_agent_rsp_fifo_out_data;                             // intensity_sram_s1_agent_rsp_fifo:out_data -> intensity_sram_s1_agent:rf_sink_data
	wire         intensity_sram_s1_agent_rsp_fifo_out_ready;                            // intensity_sram_s1_agent:rf_sink_ready -> intensity_sram_s1_agent_rsp_fifo:out_ready
	wire         intensity_sram_s1_agent_rsp_fifo_out_startofpacket;                    // intensity_sram_s1_agent_rsp_fifo:out_startofpacket -> intensity_sram_s1_agent:rf_sink_startofpacket
	wire         intensity_sram_s1_agent_rsp_fifo_out_endofpacket;                      // intensity_sram_s1_agent_rsp_fifo:out_endofpacket -> intensity_sram_s1_agent:rf_sink_endofpacket
	wire         dma_2_read_master_agent_cp_valid;                                      // dma_2_read_master_agent:cp_valid -> router:sink_valid
	wire  [97:0] dma_2_read_master_agent_cp_data;                                       // dma_2_read_master_agent:cp_data -> router:sink_data
	wire         dma_2_read_master_agent_cp_ready;                                      // router:sink_ready -> dma_2_read_master_agent:cp_ready
	wire         dma_2_read_master_agent_cp_startofpacket;                              // dma_2_read_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire         dma_2_read_master_agent_cp_endofpacket;                                // dma_2_read_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire         router_src_valid;                                                      // router:src_valid -> cmd_demux:sink_valid
	wire  [97:0] router_src_data;                                                       // router:src_data -> cmd_demux:sink_data
	wire         router_src_ready;                                                      // cmd_demux:sink_ready -> router:src_ready
	wire   [1:0] router_src_channel;                                                    // router:src_channel -> cmd_demux:sink_channel
	wire         router_src_startofpacket;                                              // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire         router_src_endofpacket;                                                // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire         dma_1_write_master_agent_cp_valid;                                     // dma_1_write_master_agent:cp_valid -> router_001:sink_valid
	wire  [97:0] dma_1_write_master_agent_cp_data;                                      // dma_1_write_master_agent:cp_data -> router_001:sink_data
	wire         dma_1_write_master_agent_cp_ready;                                     // router_001:sink_ready -> dma_1_write_master_agent:cp_ready
	wire         dma_1_write_master_agent_cp_startofpacket;                             // dma_1_write_master_agent:cp_startofpacket -> router_001:sink_startofpacket
	wire         dma_1_write_master_agent_cp_endofpacket;                               // dma_1_write_master_agent:cp_endofpacket -> router_001:sink_endofpacket
	wire         router_001_src_valid;                                                  // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [97:0] router_001_src_data;                                                   // router_001:src_data -> cmd_demux_001:sink_data
	wire         router_001_src_ready;                                                  // cmd_demux_001:sink_ready -> router_001:src_ready
	wire   [1:0] router_001_src_channel;                                                // router_001:src_channel -> cmd_demux_001:sink_channel
	wire         router_001_src_startofpacket;                                          // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire         router_001_src_endofpacket;                                            // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire         intensity_sram_s1_agent_rp_valid;                                      // intensity_sram_s1_agent:rp_valid -> router_002:sink_valid
	wire  [70:0] intensity_sram_s1_agent_rp_data;                                       // intensity_sram_s1_agent:rp_data -> router_002:sink_data
	wire         intensity_sram_s1_agent_rp_ready;                                      // router_002:sink_ready -> intensity_sram_s1_agent:rp_ready
	wire         intensity_sram_s1_agent_rp_startofpacket;                              // intensity_sram_s1_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire         intensity_sram_s1_agent_rp_endofpacket;                                // intensity_sram_s1_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire         intensity_sram_s1_burst_adapter_source0_valid;                         // intensity_sram_s1_burst_adapter:source0_valid -> intensity_sram_s1_agent:cp_valid
	wire  [70:0] intensity_sram_s1_burst_adapter_source0_data;                          // intensity_sram_s1_burst_adapter:source0_data -> intensity_sram_s1_agent:cp_data
	wire         intensity_sram_s1_burst_adapter_source0_ready;                         // intensity_sram_s1_agent:cp_ready -> intensity_sram_s1_burst_adapter:source0_ready
	wire   [1:0] intensity_sram_s1_burst_adapter_source0_channel;                       // intensity_sram_s1_burst_adapter:source0_channel -> intensity_sram_s1_agent:cp_channel
	wire         intensity_sram_s1_burst_adapter_source0_startofpacket;                 // intensity_sram_s1_burst_adapter:source0_startofpacket -> intensity_sram_s1_agent:cp_startofpacket
	wire         intensity_sram_s1_burst_adapter_source0_endofpacket;                   // intensity_sram_s1_burst_adapter:source0_endofpacket -> intensity_sram_s1_agent:cp_endofpacket
	wire         cmd_demux_src0_valid;                                                  // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [97:0] cmd_demux_src0_data;                                                   // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire         cmd_demux_src0_ready;                                                  // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire   [1:0] cmd_demux_src0_channel;                                                // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire         cmd_demux_src0_startofpacket;                                          // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire         cmd_demux_src0_endofpacket;                                            // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire         cmd_demux_001_src0_valid;                                              // cmd_demux_001:src0_valid -> cmd_mux:sink1_valid
	wire  [97:0] cmd_demux_001_src0_data;                                               // cmd_demux_001:src0_data -> cmd_mux:sink1_data
	wire         cmd_demux_001_src0_ready;                                              // cmd_mux:sink1_ready -> cmd_demux_001:src0_ready
	wire   [1:0] cmd_demux_001_src0_channel;                                            // cmd_demux_001:src0_channel -> cmd_mux:sink1_channel
	wire         cmd_demux_001_src0_startofpacket;                                      // cmd_demux_001:src0_startofpacket -> cmd_mux:sink1_startofpacket
	wire         cmd_demux_001_src0_endofpacket;                                        // cmd_demux_001:src0_endofpacket -> cmd_mux:sink1_endofpacket
	wire         rsp_demux_src0_valid;                                                  // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [97:0] rsp_demux_src0_data;                                                   // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire         rsp_demux_src0_ready;                                                  // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire   [1:0] rsp_demux_src0_channel;                                                // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire         rsp_demux_src0_startofpacket;                                          // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire         rsp_demux_src0_endofpacket;                                            // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire         rsp_demux_src1_valid;                                                  // rsp_demux:src1_valid -> rsp_mux_001:sink0_valid
	wire  [97:0] rsp_demux_src1_data;                                                   // rsp_demux:src1_data -> rsp_mux_001:sink0_data
	wire         rsp_demux_src1_ready;                                                  // rsp_mux_001:sink0_ready -> rsp_demux:src1_ready
	wire   [1:0] rsp_demux_src1_channel;                                                // rsp_demux:src1_channel -> rsp_mux_001:sink0_channel
	wire         rsp_demux_src1_startofpacket;                                          // rsp_demux:src1_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire         rsp_demux_src1_endofpacket;                                            // rsp_demux:src1_endofpacket -> rsp_mux_001:sink0_endofpacket
	wire         router_002_src_valid;                                                  // router_002:src_valid -> intensity_sram_s1_rsp_width_adapter:in_valid
	wire  [70:0] router_002_src_data;                                                   // router_002:src_data -> intensity_sram_s1_rsp_width_adapter:in_data
	wire         router_002_src_ready;                                                  // intensity_sram_s1_rsp_width_adapter:in_ready -> router_002:src_ready
	wire   [1:0] router_002_src_channel;                                                // router_002:src_channel -> intensity_sram_s1_rsp_width_adapter:in_channel
	wire         router_002_src_startofpacket;                                          // router_002:src_startofpacket -> intensity_sram_s1_rsp_width_adapter:in_startofpacket
	wire         router_002_src_endofpacket;                                            // router_002:src_endofpacket -> intensity_sram_s1_rsp_width_adapter:in_endofpacket
	wire         intensity_sram_s1_rsp_width_adapter_src_valid;                         // intensity_sram_s1_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [97:0] intensity_sram_s1_rsp_width_adapter_src_data;                          // intensity_sram_s1_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire         intensity_sram_s1_rsp_width_adapter_src_ready;                         // rsp_demux:sink_ready -> intensity_sram_s1_rsp_width_adapter:out_ready
	wire   [1:0] intensity_sram_s1_rsp_width_adapter_src_channel;                       // intensity_sram_s1_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire         intensity_sram_s1_rsp_width_adapter_src_startofpacket;                 // intensity_sram_s1_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire         intensity_sram_s1_rsp_width_adapter_src_endofpacket;                   // intensity_sram_s1_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire         cmd_mux_src_valid;                                                     // cmd_mux:src_valid -> intensity_sram_s1_cmd_width_adapter:in_valid
	wire  [97:0] cmd_mux_src_data;                                                      // cmd_mux:src_data -> intensity_sram_s1_cmd_width_adapter:in_data
	wire         cmd_mux_src_ready;                                                     // intensity_sram_s1_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire   [1:0] cmd_mux_src_channel;                                                   // cmd_mux:src_channel -> intensity_sram_s1_cmd_width_adapter:in_channel
	wire         cmd_mux_src_startofpacket;                                             // cmd_mux:src_startofpacket -> intensity_sram_s1_cmd_width_adapter:in_startofpacket
	wire         cmd_mux_src_endofpacket;                                               // cmd_mux:src_endofpacket -> intensity_sram_s1_cmd_width_adapter:in_endofpacket
	wire         intensity_sram_s1_cmd_width_adapter_src_valid;                         // intensity_sram_s1_cmd_width_adapter:out_valid -> intensity_sram_s1_burst_adapter:sink0_valid
	wire  [70:0] intensity_sram_s1_cmd_width_adapter_src_data;                          // intensity_sram_s1_cmd_width_adapter:out_data -> intensity_sram_s1_burst_adapter:sink0_data
	wire         intensity_sram_s1_cmd_width_adapter_src_ready;                         // intensity_sram_s1_burst_adapter:sink0_ready -> intensity_sram_s1_cmd_width_adapter:out_ready
	wire   [1:0] intensity_sram_s1_cmd_width_adapter_src_channel;                       // intensity_sram_s1_cmd_width_adapter:out_channel -> intensity_sram_s1_burst_adapter:sink0_channel
	wire         intensity_sram_s1_cmd_width_adapter_src_startofpacket;                 // intensity_sram_s1_cmd_width_adapter:out_startofpacket -> intensity_sram_s1_burst_adapter:sink0_startofpacket
	wire         intensity_sram_s1_cmd_width_adapter_src_endofpacket;                   // intensity_sram_s1_cmd_width_adapter:out_endofpacket -> intensity_sram_s1_burst_adapter:sink0_endofpacket
	wire         intensity_sram_s1_agent_rdata_fifo_src_valid;                          // intensity_sram_s1_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [9:0] intensity_sram_s1_agent_rdata_fifo_src_data;                           // intensity_sram_s1_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire         intensity_sram_s1_agent_rdata_fifo_src_ready;                          // avalon_st_adapter:in_0_ready -> intensity_sram_s1_agent:rdata_fifo_src_ready
	wire         avalon_st_adapter_out_0_valid;                                         // avalon_st_adapter:out_0_valid -> intensity_sram_s1_agent:rdata_fifo_sink_valid
	wire   [9:0] avalon_st_adapter_out_0_data;                                          // avalon_st_adapter:out_0_data -> intensity_sram_s1_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_out_0_ready;                                         // intensity_sram_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire   [0:0] avalon_st_adapter_out_0_error;                                         // avalon_st_adapter:out_0_error -> intensity_sram_s1_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (28),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (28),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) dma_2_read_master_translator (
		.clk                    (System_PLL_sys_clk_clk),                                               //                       clk.clk
		.reset                  (dma_2_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address            (dma_2_read_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (dma_2_read_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (dma_2_read_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (dma_2_read_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (dma_2_read_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (dma_2_read_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (dma_2_read_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (dma_2_read_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (dma_2_read_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (dma_2_read_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (dma_2_read_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (dma_2_read_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (dma_2_read_master_waitrequest),                                        //                          .waitrequest
		.av_chipselect          (dma_2_read_master_chipselect),                                         //                          .chipselect
		.av_read                (dma_2_read_master_read),                                               //                          .read
		.av_readdata            (dma_2_read_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (dma_2_read_master_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                 //               (terminated)
		.av_byteenable          (4'b1111),                                                              //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                 //               (terminated)
		.av_begintransfer       (1'b0),                                                                 //               (terminated)
		.av_write               (1'b0),                                                                 //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                 //               (terminated)
		.av_lock                (1'b0),                                                                 //               (terminated)
		.av_debugaccess         (1'b0),                                                                 //               (terminated)
		.uav_clken              (),                                                                     //               (terminated)
		.av_clken               (1'b1),                                                                 //               (terminated)
		.uav_response           (2'b00),                                                                //               (terminated)
		.av_response            (),                                                                     //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                 //               (terminated)
		.av_writeresponsevalid  ()                                                                      //               (terminated)
	);

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (28),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (28),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) dma_1_write_master_translator (
		.clk                    (System_PLL_sys_clk_clk),                                                //                       clk.clk
		.reset                  (dma_2_reset_reset_bridge_in_reset_reset),                               //                     reset.reset
		.uav_address            (dma_1_write_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (dma_1_write_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (dma_1_write_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (dma_1_write_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (dma_1_write_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (dma_1_write_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (dma_1_write_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (dma_1_write_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (dma_1_write_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (dma_1_write_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (dma_1_write_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (dma_1_write_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (dma_1_write_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (dma_1_write_master_byteenable),                                         //                          .byteenable
		.av_chipselect          (dma_1_write_master_chipselect),                                         //                          .chipselect
		.av_write               (dma_1_write_master_write),                                              //                          .write
		.av_writedata           (dma_1_write_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                  //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                  //               (terminated)
		.av_begintransfer       (1'b0),                                                                  //               (terminated)
		.av_read                (1'b0),                                                                  //               (terminated)
		.av_readdata            (),                                                                      //               (terminated)
		.av_readdatavalid       (),                                                                      //               (terminated)
		.av_lock                (1'b0),                                                                  //               (terminated)
		.av_debugaccess         (1'b0),                                                                  //               (terminated)
		.uav_clken              (),                                                                      //               (terminated)
		.av_clken               (1'b1),                                                                  //               (terminated)
		.uav_response           (2'b00),                                                                 //               (terminated)
		.av_response            (),                                                                      //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                  //               (terminated)
		.av_writeresponsevalid  ()                                                                       //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (16),
		.AV_DATA_W                      (8),
		.UAV_DATA_W                     (8),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (1),
		.UAV_ADDRESS_W                  (28),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (1),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) intensity_sram_s1_translator (
		.clk                    (System_PLL_sys_clk_clk),                   //                      clk.clk
		.reset                  (dma_2_reset_reset_bridge_in_reset_reset),  //                    reset.reset
		.uav_address            (intensity_sram_s1_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (intensity_sram_s1_agent_m0_burstcount),    //                         .burstcount
		.uav_read               (intensity_sram_s1_agent_m0_read),          //                         .read
		.uav_write              (intensity_sram_s1_agent_m0_write),         //                         .write
		.uav_waitrequest        (intensity_sram_s1_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (intensity_sram_s1_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (intensity_sram_s1_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata           (intensity_sram_s1_agent_m0_readdata),      //                         .readdata
		.uav_writedata          (intensity_sram_s1_agent_m0_writedata),     //                         .writedata
		.uav_lock               (intensity_sram_s1_agent_m0_lock),          //                         .lock
		.uav_debugaccess        (intensity_sram_s1_agent_m0_debugaccess),   //                         .debugaccess
		.av_address             (intensity_sram_s1_address),                //      avalon_anti_slave_0.address
		.av_write               (intensity_sram_s1_write),                  //                         .write
		.av_readdata            (intensity_sram_s1_readdata),               //                         .readdata
		.av_writedata           (intensity_sram_s1_writedata),              //                         .writedata
		.av_chipselect          (intensity_sram_s1_chipselect),             //                         .chipselect
		.av_clken               (intensity_sram_s1_clken),                  //                         .clken
		.av_read                (),                                         //              (terminated)
		.av_begintransfer       (),                                         //              (terminated)
		.av_beginbursttransfer  (),                                         //              (terminated)
		.av_burstcount          (),                                         //              (terminated)
		.av_byteenable          (),                                         //              (terminated)
		.av_readdatavalid       (1'b0),                                     //              (terminated)
		.av_waitrequest         (1'b0),                                     //              (terminated)
		.av_writebyteenable     (),                                         //              (terminated)
		.av_lock                (),                                         //              (terminated)
		.uav_clken              (1'b0),                                     //              (terminated)
		.av_debugaccess         (),                                         //              (terminated)
		.av_outputenable        (),                                         //              (terminated)
		.uav_response           (),                                         //              (terminated)
		.av_response            (2'b00),                                    //              (terminated)
		.uav_writeresponsevalid (),                                         //              (terminated)
		.av_writeresponsevalid  (1'b0)                                      //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (97),
		.PKT_ORI_BURST_SIZE_L      (95),
		.PKT_RESPONSE_STATUS_H     (94),
		.PKT_RESPONSE_STATUS_L     (93),
		.PKT_QOS_H                 (82),
		.PKT_QOS_L                 (82),
		.PKT_DATA_SIDEBAND_H       (80),
		.PKT_DATA_SIDEBAND_L       (80),
		.PKT_ADDR_SIDEBAND_H       (79),
		.PKT_ADDR_SIDEBAND_L       (79),
		.PKT_BURST_TYPE_H          (78),
		.PKT_BURST_TYPE_L          (77),
		.PKT_CACHE_H               (92),
		.PKT_CACHE_L               (89),
		.PKT_THREAD_ID_H           (85),
		.PKT_THREAD_ID_L           (85),
		.PKT_BURST_SIZE_H          (76),
		.PKT_BURST_SIZE_L          (74),
		.PKT_TRANS_EXCLUSIVE       (69),
		.PKT_TRANS_LOCK            (68),
		.PKT_BEGIN_BURST           (81),
		.PKT_PROTECTION_H          (88),
		.PKT_PROTECTION_L          (86),
		.PKT_BURSTWRAP_H           (73),
		.PKT_BURSTWRAP_L           (73),
		.PKT_BYTE_CNT_H            (72),
		.PKT_BYTE_CNT_L            (70),
		.PKT_ADDR_H                (63),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (64),
		.PKT_TRANS_POSTED          (65),
		.PKT_TRANS_WRITE           (66),
		.PKT_TRANS_READ            (67),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (83),
		.PKT_SRC_ID_L              (83),
		.PKT_DEST_ID_H             (84),
		.PKT_DEST_ID_L             (84),
		.ST_DATA_W                 (98),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (1),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) dma_2_read_master_agent (
		.clk                   (System_PLL_sys_clk_clk),                                               //       clk.clk
		.reset                 (dma_2_reset_reset_bridge_in_reset_reset),                              // clk_reset.reset
		.av_address            (dma_2_read_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (dma_2_read_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (dma_2_read_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (dma_2_read_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (dma_2_read_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (dma_2_read_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (dma_2_read_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (dma_2_read_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (dma_2_read_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (dma_2_read_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (dma_2_read_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (dma_2_read_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (dma_2_read_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (dma_2_read_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (dma_2_read_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (dma_2_read_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                    //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                     //          .data
		.rp_channel            (rsp_mux_src_channel),                                                  //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                            //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                              //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                    //          .ready
		.av_response           (),                                                                     // (terminated)
		.av_writeresponsevalid ()                                                                      // (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (97),
		.PKT_ORI_BURST_SIZE_L      (95),
		.PKT_RESPONSE_STATUS_H     (94),
		.PKT_RESPONSE_STATUS_L     (93),
		.PKT_QOS_H                 (82),
		.PKT_QOS_L                 (82),
		.PKT_DATA_SIDEBAND_H       (80),
		.PKT_DATA_SIDEBAND_L       (80),
		.PKT_ADDR_SIDEBAND_H       (79),
		.PKT_ADDR_SIDEBAND_L       (79),
		.PKT_BURST_TYPE_H          (78),
		.PKT_BURST_TYPE_L          (77),
		.PKT_CACHE_H               (92),
		.PKT_CACHE_L               (89),
		.PKT_THREAD_ID_H           (85),
		.PKT_THREAD_ID_L           (85),
		.PKT_BURST_SIZE_H          (76),
		.PKT_BURST_SIZE_L          (74),
		.PKT_TRANS_EXCLUSIVE       (69),
		.PKT_TRANS_LOCK            (68),
		.PKT_BEGIN_BURST           (81),
		.PKT_PROTECTION_H          (88),
		.PKT_PROTECTION_L          (86),
		.PKT_BURSTWRAP_H           (73),
		.PKT_BURSTWRAP_L           (73),
		.PKT_BYTE_CNT_H            (72),
		.PKT_BYTE_CNT_L            (70),
		.PKT_ADDR_H                (63),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (64),
		.PKT_TRANS_POSTED          (65),
		.PKT_TRANS_WRITE           (66),
		.PKT_TRANS_READ            (67),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (83),
		.PKT_SRC_ID_L              (83),
		.PKT_DEST_ID_H             (84),
		.PKT_DEST_ID_L             (84),
		.ST_DATA_W                 (98),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) dma_1_write_master_agent (
		.clk                   (System_PLL_sys_clk_clk),                                                //       clk.clk
		.reset                 (dma_2_reset_reset_bridge_in_reset_reset),                               // clk_reset.reset
		.av_address            (dma_1_write_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (dma_1_write_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (dma_1_write_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (dma_1_write_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (dma_1_write_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (dma_1_write_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (dma_1_write_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (dma_1_write_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (dma_1_write_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (dma_1_write_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (dma_1_write_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (dma_1_write_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (dma_1_write_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (dma_1_write_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (dma_1_write_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (dma_1_write_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_001_src_valid),                                                 //        rp.valid
		.rp_data               (rsp_mux_001_src_data),                                                  //          .data
		.rp_channel            (rsp_mux_001_src_channel),                                               //          .channel
		.rp_startofpacket      (rsp_mux_001_src_startofpacket),                                         //          .startofpacket
		.rp_endofpacket        (rsp_mux_001_src_endofpacket),                                           //          .endofpacket
		.rp_ready              (rsp_mux_001_src_ready),                                                 //          .ready
		.av_response           (),                                                                      // (terminated)
		.av_writeresponsevalid ()                                                                       // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (70),
		.PKT_ORI_BURST_SIZE_L      (68),
		.PKT_RESPONSE_STATUS_H     (67),
		.PKT_RESPONSE_STATUS_L     (66),
		.PKT_BURST_SIZE_H          (49),
		.PKT_BURST_SIZE_L          (47),
		.PKT_TRANS_LOCK            (41),
		.PKT_BEGIN_BURST           (54),
		.PKT_PROTECTION_H          (61),
		.PKT_PROTECTION_L          (59),
		.PKT_BURSTWRAP_H           (46),
		.PKT_BURSTWRAP_L           (46),
		.PKT_BYTE_CNT_H            (45),
		.PKT_BYTE_CNT_L            (43),
		.PKT_ADDR_H                (36),
		.PKT_ADDR_L                (9),
		.PKT_TRANS_COMPRESSED_READ (37),
		.PKT_TRANS_POSTED          (38),
		.PKT_TRANS_WRITE           (39),
		.PKT_TRANS_READ            (40),
		.PKT_DATA_H                (7),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (8),
		.PKT_BYTEEN_L              (8),
		.PKT_SRC_ID_H              (56),
		.PKT_SRC_ID_L              (56),
		.PKT_DEST_ID_H             (57),
		.PKT_DEST_ID_L             (57),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (71),
		.AVS_BURSTCOUNT_W          (1),
		.SUPPRESS_0_BYTEEN_CMD     (1),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) intensity_sram_s1_agent (
		.clk                     (System_PLL_sys_clk_clk),                                //             clk.clk
		.reset                   (dma_2_reset_reset_bridge_in_reset_reset),               //       clk_reset.reset
		.m0_address              (intensity_sram_s1_agent_m0_address),                    //              m0.address
		.m0_burstcount           (intensity_sram_s1_agent_m0_burstcount),                 //                .burstcount
		.m0_byteenable           (intensity_sram_s1_agent_m0_byteenable),                 //                .byteenable
		.m0_debugaccess          (intensity_sram_s1_agent_m0_debugaccess),                //                .debugaccess
		.m0_lock                 (intensity_sram_s1_agent_m0_lock),                       //                .lock
		.m0_readdata             (intensity_sram_s1_agent_m0_readdata),                   //                .readdata
		.m0_readdatavalid        (intensity_sram_s1_agent_m0_readdatavalid),              //                .readdatavalid
		.m0_read                 (intensity_sram_s1_agent_m0_read),                       //                .read
		.m0_waitrequest          (intensity_sram_s1_agent_m0_waitrequest),                //                .waitrequest
		.m0_writedata            (intensity_sram_s1_agent_m0_writedata),                  //                .writedata
		.m0_write                (intensity_sram_s1_agent_m0_write),                      //                .write
		.rp_endofpacket          (intensity_sram_s1_agent_rp_endofpacket),                //              rp.endofpacket
		.rp_ready                (intensity_sram_s1_agent_rp_ready),                      //                .ready
		.rp_valid                (intensity_sram_s1_agent_rp_valid),                      //                .valid
		.rp_data                 (intensity_sram_s1_agent_rp_data),                       //                .data
		.rp_startofpacket        (intensity_sram_s1_agent_rp_startofpacket),              //                .startofpacket
		.cp_ready                (intensity_sram_s1_burst_adapter_source0_ready),         //              cp.ready
		.cp_valid                (intensity_sram_s1_burst_adapter_source0_valid),         //                .valid
		.cp_data                 (intensity_sram_s1_burst_adapter_source0_data),          //                .data
		.cp_startofpacket        (intensity_sram_s1_burst_adapter_source0_startofpacket), //                .startofpacket
		.cp_endofpacket          (intensity_sram_s1_burst_adapter_source0_endofpacket),   //                .endofpacket
		.cp_channel              (intensity_sram_s1_burst_adapter_source0_channel),       //                .channel
		.rf_sink_ready           (intensity_sram_s1_agent_rsp_fifo_out_ready),            //         rf_sink.ready
		.rf_sink_valid           (intensity_sram_s1_agent_rsp_fifo_out_valid),            //                .valid
		.rf_sink_startofpacket   (intensity_sram_s1_agent_rsp_fifo_out_startofpacket),    //                .startofpacket
		.rf_sink_endofpacket     (intensity_sram_s1_agent_rsp_fifo_out_endofpacket),      //                .endofpacket
		.rf_sink_data            (intensity_sram_s1_agent_rsp_fifo_out_data),             //                .data
		.rf_source_ready         (intensity_sram_s1_agent_rf_source_ready),               //       rf_source.ready
		.rf_source_valid         (intensity_sram_s1_agent_rf_source_valid),               //                .valid
		.rf_source_startofpacket (intensity_sram_s1_agent_rf_source_startofpacket),       //                .startofpacket
		.rf_source_endofpacket   (intensity_sram_s1_agent_rf_source_endofpacket),         //                .endofpacket
		.rf_source_data          (intensity_sram_s1_agent_rf_source_data),                //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                         // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                         //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                          //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                         //                .error
		.rdata_fifo_src_ready    (intensity_sram_s1_agent_rdata_fifo_src_ready),          //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (intensity_sram_s1_agent_rdata_fifo_src_valid),          //                .valid
		.rdata_fifo_src_data     (intensity_sram_s1_agent_rdata_fifo_src_data),           //                .data
		.m0_response             (2'b00),                                                 //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                   //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (72),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) intensity_sram_s1_agent_rsp_fifo (
		.clk               (System_PLL_sys_clk_clk),                             //       clk.clk
		.reset             (dma_2_reset_reset_bridge_in_reset_reset),            // clk_reset.reset
		.in_data           (intensity_sram_s1_agent_rf_source_data),             //        in.data
		.in_valid          (intensity_sram_s1_agent_rf_source_valid),            //          .valid
		.in_ready          (intensity_sram_s1_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (intensity_sram_s1_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (intensity_sram_s1_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (intensity_sram_s1_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (intensity_sram_s1_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (intensity_sram_s1_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (intensity_sram_s1_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (intensity_sram_s1_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                              // (terminated)
		.csr_read          (1'b0),                                               // (terminated)
		.csr_write         (1'b0),                                               // (terminated)
		.csr_readdata      (),                                                   // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),               // (terminated)
		.almost_full_data  (),                                                   // (terminated)
		.almost_empty_data (),                                                   // (terminated)
		.in_empty          (1'b0),                                               // (terminated)
		.out_empty         (),                                                   // (terminated)
		.in_error          (1'b0),                                               // (terminated)
		.out_error         (),                                                   // (terminated)
		.in_channel        (1'b0),                                               // (terminated)
		.out_channel       ()                                                    // (terminated)
	);

	Computer_System_mm_interconnect_3_router router (
		.sink_ready         (dma_2_read_master_agent_cp_ready),         //      sink.ready
		.sink_valid         (dma_2_read_master_agent_cp_valid),         //          .valid
		.sink_data          (dma_2_read_master_agent_cp_data),          //          .data
		.sink_startofpacket (dma_2_read_master_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (dma_2_read_master_agent_cp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                   //       clk.clk
		.reset              (dma_2_reset_reset_bridge_in_reset_reset),  // clk_reset.reset
		.src_ready          (router_src_ready),                         //       src.ready
		.src_valid          (router_src_valid),                         //          .valid
		.src_data           (router_src_data),                          //          .data
		.src_channel        (router_src_channel),                       //          .channel
		.src_startofpacket  (router_src_startofpacket),                 //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                    //          .endofpacket
	);

	Computer_System_mm_interconnect_3_router router_001 (
		.sink_ready         (dma_1_write_master_agent_cp_ready),         //      sink.ready
		.sink_valid         (dma_1_write_master_agent_cp_valid),         //          .valid
		.sink_data          (dma_1_write_master_agent_cp_data),          //          .data
		.sink_startofpacket (dma_1_write_master_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (dma_1_write_master_agent_cp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                    //       clk.clk
		.reset              (dma_2_reset_reset_bridge_in_reset_reset),   // clk_reset.reset
		.src_ready          (router_001_src_ready),                      //       src.ready
		.src_valid          (router_001_src_valid),                      //          .valid
		.src_data           (router_001_src_data),                       //          .data
		.src_channel        (router_001_src_channel),                    //          .channel
		.src_startofpacket  (router_001_src_startofpacket),              //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                 //          .endofpacket
	);

	Computer_System_mm_interconnect_3_router_002 router_002 (
		.sink_ready         (intensity_sram_s1_agent_rp_ready),         //      sink.ready
		.sink_valid         (intensity_sram_s1_agent_rp_valid),         //          .valid
		.sink_data          (intensity_sram_s1_agent_rp_data),          //          .data
		.sink_startofpacket (intensity_sram_s1_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (intensity_sram_s1_agent_rp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                   //       clk.clk
		.reset              (dma_2_reset_reset_bridge_in_reset_reset),  // clk_reset.reset
		.src_ready          (router_002_src_ready),                     //       src.ready
		.src_valid          (router_002_src_valid),                     //          .valid
		.src_data           (router_002_src_data),                      //          .data
		.src_channel        (router_002_src_channel),                   //          .channel
		.src_startofpacket  (router_002_src_startofpacket),             //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (36),
		.PKT_ADDR_L                (9),
		.PKT_BEGIN_BURST           (54),
		.PKT_BYTE_CNT_H            (45),
		.PKT_BYTE_CNT_L            (43),
		.PKT_BYTEEN_H              (8),
		.PKT_BYTEEN_L              (8),
		.PKT_BURST_SIZE_H          (49),
		.PKT_BURST_SIZE_L          (47),
		.PKT_BURST_TYPE_H          (51),
		.PKT_BURST_TYPE_L          (50),
		.PKT_BURSTWRAP_H           (46),
		.PKT_BURSTWRAP_L           (46),
		.PKT_TRANS_COMPRESSED_READ (37),
		.PKT_TRANS_WRITE           (39),
		.PKT_TRANS_READ            (40),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (71),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (43),
		.OUT_BURSTWRAP_H           (46),
		.COMPRESSED_READ_SUPPORT   (0),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1")
	) intensity_sram_s1_burst_adapter (
		.clk                   (System_PLL_sys_clk_clk),                                //       cr0.clk
		.reset                 (dma_2_reset_reset_bridge_in_reset_reset),               // cr0_reset.reset
		.sink0_valid           (intensity_sram_s1_cmd_width_adapter_src_valid),         //     sink0.valid
		.sink0_data            (intensity_sram_s1_cmd_width_adapter_src_data),          //          .data
		.sink0_channel         (intensity_sram_s1_cmd_width_adapter_src_channel),       //          .channel
		.sink0_startofpacket   (intensity_sram_s1_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.sink0_endofpacket     (intensity_sram_s1_cmd_width_adapter_src_endofpacket),   //          .endofpacket
		.sink0_ready           (intensity_sram_s1_cmd_width_adapter_src_ready),         //          .ready
		.source0_valid         (intensity_sram_s1_burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (intensity_sram_s1_burst_adapter_source0_data),          //          .data
		.source0_channel       (intensity_sram_s1_burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (intensity_sram_s1_burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (intensity_sram_s1_burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (intensity_sram_s1_burst_adapter_source0_ready)          //          .ready
	);

	Computer_System_mm_interconnect_3_cmd_demux cmd_demux (
		.clk                (System_PLL_sys_clk_clk),                  //       clk.clk
		.reset              (dma_2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                        //      sink.ready
		.sink_channel       (router_src_channel),                      //          .channel
		.sink_data          (router_src_data),                         //          .data
		.sink_startofpacket (router_src_startofpacket),                //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                  //          .endofpacket
		.sink_valid         (router_src_valid),                        //          .valid
		.src0_ready         (cmd_demux_src0_ready),                    //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                    //          .valid
		.src0_data          (cmd_demux_src0_data),                     //          .data
		.src0_channel       (cmd_demux_src0_channel),                  //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),            //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)               //          .endofpacket
	);

	Computer_System_mm_interconnect_3_cmd_demux cmd_demux_001 (
		.clk                (System_PLL_sys_clk_clk),                  //       clk.clk
		.reset              (dma_2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                    //      sink.ready
		.sink_channel       (router_001_src_channel),                  //          .channel
		.sink_data          (router_001_src_data),                     //          .data
		.sink_startofpacket (router_001_src_startofpacket),            //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),              //          .endofpacket
		.sink_valid         (router_001_src_valid),                    //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                //          .valid
		.src0_data          (cmd_demux_001_src0_data),                 //          .data
		.src0_channel       (cmd_demux_001_src0_channel),              //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),        //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)           //          .endofpacket
	);

	Computer_System_mm_interconnect_3_cmd_mux cmd_mux (
		.clk                 (System_PLL_sys_clk_clk),                  //       clk.clk
		.reset               (dma_2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                       //       src.ready
		.src_valid           (cmd_mux_src_valid),                       //          .valid
		.src_data            (cmd_mux_src_data),                        //          .data
		.src_channel         (cmd_mux_src_channel),                     //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),               //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                 //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                    //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                    //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                  //          .channel
		.sink0_data          (cmd_demux_src0_data),                     //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),            //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket),              //          .endofpacket
		.sink1_ready         (cmd_demux_001_src0_ready),                //     sink1.ready
		.sink1_valid         (cmd_demux_001_src0_valid),                //          .valid
		.sink1_channel       (cmd_demux_001_src0_channel),              //          .channel
		.sink1_data          (cmd_demux_001_src0_data),                 //          .data
		.sink1_startofpacket (cmd_demux_001_src0_startofpacket),        //          .startofpacket
		.sink1_endofpacket   (cmd_demux_001_src0_endofpacket)           //          .endofpacket
	);

	Computer_System_mm_interconnect_3_rsp_demux rsp_demux (
		.clk                (System_PLL_sys_clk_clk),                                //       clk.clk
		.reset              (dma_2_reset_reset_bridge_in_reset_reset),               // clk_reset.reset
		.sink_ready         (intensity_sram_s1_rsp_width_adapter_src_ready),         //      sink.ready
		.sink_channel       (intensity_sram_s1_rsp_width_adapter_src_channel),       //          .channel
		.sink_data          (intensity_sram_s1_rsp_width_adapter_src_data),          //          .data
		.sink_startofpacket (intensity_sram_s1_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.sink_endofpacket   (intensity_sram_s1_rsp_width_adapter_src_endofpacket),   //          .endofpacket
		.sink_valid         (intensity_sram_s1_rsp_width_adapter_src_valid),         //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                  //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                  //          .valid
		.src0_data          (rsp_demux_src0_data),                                   //          .data
		.src0_channel       (rsp_demux_src0_channel),                                //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                          //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),                            //          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                                  //      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                                  //          .valid
		.src1_data          (rsp_demux_src1_data),                                   //          .data
		.src1_channel       (rsp_demux_src1_channel),                                //          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),                          //          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)                             //          .endofpacket
	);

	Computer_System_mm_interconnect_3_rsp_mux rsp_mux (
		.clk                 (System_PLL_sys_clk_clk),                  //       clk.clk
		.reset               (dma_2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                       //       src.ready
		.src_valid           (rsp_mux_src_valid),                       //          .valid
		.src_data            (rsp_mux_src_data),                        //          .data
		.src_channel         (rsp_mux_src_channel),                     //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),               //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                 //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                    //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                    //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                  //          .channel
		.sink0_data          (rsp_demux_src0_data),                     //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),            //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)               //          .endofpacket
	);

	Computer_System_mm_interconnect_3_rsp_mux rsp_mux_001 (
		.clk                 (System_PLL_sys_clk_clk),                  //       clk.clk
		.reset               (dma_2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                   //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                   //          .valid
		.src_data            (rsp_mux_001_src_data),                    //          .data
		.src_channel         (rsp_mux_001_src_channel),                 //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),           //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),             //          .endofpacket
		.sink0_ready         (rsp_demux_src1_ready),                    //     sink0.ready
		.sink0_valid         (rsp_demux_src1_valid),                    //          .valid
		.sink0_channel       (rsp_demux_src1_channel),                  //          .channel
		.sink0_data          (rsp_demux_src1_data),                     //          .data
		.sink0_startofpacket (rsp_demux_src1_startofpacket),            //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src1_endofpacket)               //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (36),
		.IN_PKT_ADDR_L                 (9),
		.IN_PKT_DATA_H                 (7),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (8),
		.IN_PKT_BYTEEN_L               (8),
		.IN_PKT_BYTE_CNT_H             (45),
		.IN_PKT_BYTE_CNT_L             (43),
		.IN_PKT_TRANS_COMPRESSED_READ  (37),
		.IN_PKT_TRANS_WRITE            (39),
		.IN_PKT_BURSTWRAP_H            (46),
		.IN_PKT_BURSTWRAP_L            (46),
		.IN_PKT_BURST_SIZE_H           (49),
		.IN_PKT_BURST_SIZE_L           (47),
		.IN_PKT_RESPONSE_STATUS_H      (67),
		.IN_PKT_RESPONSE_STATUS_L      (66),
		.IN_PKT_TRANS_EXCLUSIVE        (42),
		.IN_PKT_BURST_TYPE_H           (51),
		.IN_PKT_BURST_TYPE_L           (50),
		.IN_PKT_ORI_BURST_SIZE_L       (68),
		.IN_PKT_ORI_BURST_SIZE_H       (70),
		.IN_ST_DATA_W                  (71),
		.OUT_PKT_ADDR_H                (63),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (72),
		.OUT_PKT_BYTE_CNT_L            (70),
		.OUT_PKT_TRANS_COMPRESSED_READ (64),
		.OUT_PKT_BURST_SIZE_H          (76),
		.OUT_PKT_BURST_SIZE_L          (74),
		.OUT_PKT_RESPONSE_STATUS_H     (94),
		.OUT_PKT_RESPONSE_STATUS_L     (93),
		.OUT_PKT_TRANS_EXCLUSIVE       (69),
		.OUT_PKT_BURST_TYPE_H          (78),
		.OUT_PKT_BURST_TYPE_L          (77),
		.OUT_PKT_ORI_BURST_SIZE_L      (95),
		.OUT_PKT_ORI_BURST_SIZE_H      (97),
		.OUT_ST_DATA_W                 (98),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (1),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) intensity_sram_s1_rsp_width_adapter (
		.clk                  (System_PLL_sys_clk_clk),                                //       clk.clk
		.reset                (dma_2_reset_reset_bridge_in_reset_reset),               // clk_reset.reset
		.in_valid             (router_002_src_valid),                                  //      sink.valid
		.in_channel           (router_002_src_channel),                                //          .channel
		.in_startofpacket     (router_002_src_startofpacket),                          //          .startofpacket
		.in_endofpacket       (router_002_src_endofpacket),                            //          .endofpacket
		.in_ready             (router_002_src_ready),                                  //          .ready
		.in_data              (router_002_src_data),                                   //          .data
		.out_endofpacket      (intensity_sram_s1_rsp_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (intensity_sram_s1_rsp_width_adapter_src_data),          //          .data
		.out_channel          (intensity_sram_s1_rsp_width_adapter_src_channel),       //          .channel
		.out_valid            (intensity_sram_s1_rsp_width_adapter_src_valid),         //          .valid
		.out_ready            (intensity_sram_s1_rsp_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (intensity_sram_s1_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                                 // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (63),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (72),
		.IN_PKT_BYTE_CNT_L             (70),
		.IN_PKT_TRANS_COMPRESSED_READ  (64),
		.IN_PKT_TRANS_WRITE            (66),
		.IN_PKT_BURSTWRAP_H            (73),
		.IN_PKT_BURSTWRAP_L            (73),
		.IN_PKT_BURST_SIZE_H           (76),
		.IN_PKT_BURST_SIZE_L           (74),
		.IN_PKT_RESPONSE_STATUS_H      (94),
		.IN_PKT_RESPONSE_STATUS_L      (93),
		.IN_PKT_TRANS_EXCLUSIVE        (69),
		.IN_PKT_BURST_TYPE_H           (78),
		.IN_PKT_BURST_TYPE_L           (77),
		.IN_PKT_ORI_BURST_SIZE_L       (95),
		.IN_PKT_ORI_BURST_SIZE_H       (97),
		.IN_ST_DATA_W                  (98),
		.OUT_PKT_ADDR_H                (36),
		.OUT_PKT_ADDR_L                (9),
		.OUT_PKT_DATA_H                (7),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (8),
		.OUT_PKT_BYTEEN_L              (8),
		.OUT_PKT_BYTE_CNT_H            (45),
		.OUT_PKT_BYTE_CNT_L            (43),
		.OUT_PKT_TRANS_COMPRESSED_READ (37),
		.OUT_PKT_BURST_SIZE_H          (49),
		.OUT_PKT_BURST_SIZE_L          (47),
		.OUT_PKT_RESPONSE_STATUS_H     (67),
		.OUT_PKT_RESPONSE_STATUS_L     (66),
		.OUT_PKT_TRANS_EXCLUSIVE       (42),
		.OUT_PKT_BURST_TYPE_H          (51),
		.OUT_PKT_BURST_TYPE_L          (50),
		.OUT_PKT_ORI_BURST_SIZE_L      (68),
		.OUT_PKT_ORI_BURST_SIZE_H      (70),
		.OUT_ST_DATA_W                 (71),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) intensity_sram_s1_cmd_width_adapter (
		.clk                  (System_PLL_sys_clk_clk),                                //       clk.clk
		.reset                (dma_2_reset_reset_bridge_in_reset_reset),               // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                     //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                   //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                             //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                               //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                     //          .ready
		.in_data              (cmd_mux_src_data),                                      //          .data
		.out_endofpacket      (intensity_sram_s1_cmd_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (intensity_sram_s1_cmd_width_adapter_src_data),          //          .data
		.out_channel          (intensity_sram_s1_cmd_width_adapter_src_channel),       //          .channel
		.out_valid            (intensity_sram_s1_cmd_width_adapter_src_valid),         //          .valid
		.out_ready            (intensity_sram_s1_cmd_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (intensity_sram_s1_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                                 // (terminated)
	);

	Computer_System_mm_interconnect_3_avalon_st_adapter #(
		.inBitsPerSymbol (10),
		.inUsePackets    (0),
		.inDataWidth     (10),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (10),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (System_PLL_sys_clk_clk),                       // in_clk_0.clk
		.in_rst_0_reset (dma_2_reset_reset_bridge_in_reset_reset),      // in_rst_0.reset
		.in_0_data      (intensity_sram_s1_agent_rdata_fifo_src_data),  //     in_0.data
		.in_0_valid     (intensity_sram_s1_agent_rdata_fifo_src_valid), //         .valid
		.in_0_ready     (intensity_sram_s1_agent_rdata_fifo_src_ready), //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                 //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                 //         .error
	);

endmodule
